from __future__ import annotations

import logging
import uuid
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import FileResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from backend.database import get_db
from backend.models.report import Report
from backend.models.user import User
from backend.schemas.report import ReportResponse
from backend.services.auth_service import get_current_user

logger = logging.getLogger(__name__)

router = APIRouter()


@router.get(
    "",
    response_model=list[ReportResponse],
    summary="List generated reports",
    description=(
        "Returns all PDF reports that have been generated by agent runs, sorted by creation date.\n\n"
        "Filter by `company_id` to list reports for a specific company."
    ),
    response_description="Array of report metadata records",
)
async def list_reports(
    company_id: uuid.UUID | None = None,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> list[Report]:
    query = select(Report).order_by(Report.created_at.desc())
    if company_id is not None:
        query = query.where(Report.company_id == company_id)
    result = await db.execute(query)
    return list(result.scalars().all())


@router.get(
    "/{report_id}/download",
    summary="Download a report PDF",
    description=(
        "Stream the generated PDF report file directly as a browser download.\n\n"
        "The `report_id` parameter accepts either the report's own UUID **or** the "
        "agent `run_id` — if no report is found by its primary key, the endpoint "
        "falls back to a lookup by `run_id`.\n\n"
        "Returns `Content-Type: application/pdf`. "
        "Returns **404** if the report record or its file is not found on disk."
    ),
    response_description="PDF file stream",
    responses={
        200: {"content": {"application/pdf": {}}, "description": "PDF report file"},
        404: {"description": "Report not found"},
    },
)
async def download_report(
    report_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> FileResponse:
    # First try to find by report's own id
    result = await db.execute(select(Report).where(Report.id == report_id))
    report = result.scalar_one_or_none()
    # Fallback: the caller may have passed the agent run_id instead of the report id
    if report is None:
        result = await db.execute(
            select(Report)
            .where(Report.run_id == report_id)
            .order_by(Report.created_at.desc())
        )
        report = result.scalar_one_or_none()
    if report is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Report not found")

    file_path = Path(report.file_path)
    if not file_path.exists():
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Report file not found on disk")

    return FileResponse(
        path=str(file_path),
        media_type="application/pdf",
        filename=file_path.name,
    )
