import { Component, inject, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { SlicePipe } from '@angular/common';
import { ReplacePipe } from '../../shared/pipes/replace.pipe';
import { ApiService } from '../../core/services/api.service';
import { ToastService } from '../../core/services/toast.service';
import { Alert, Company } from '../../core/models';

@Component({
    selector: 'app-alerts',
    standalone: true,
    imports: [FormsModule, SlicePipe, ReplacePipe],
    template: `
    <div class="page-container">
      <div class="page-header animate-fade-in">
        <div>
          <div class="page-title">
            <div class="title-icon" style="background:rgba(245,158,11,0.12);color:var(--status-warning)">🔔</div>
            <div>
              Alerts
              <div class="page-subtitle">Risk alerts generated by AI analysis runs</div>
            </div>
          </div>
        </div>
        <div style="display:flex;gap:8px">
          <button class="btn-ghost btn-sm" (click)="loadAlerts()">↻ Refresh</button>
        </div>
      </div>

      <!-- Stats Bar -->
      <div class="section-grid cols-3 animate-fade-in-up">
        <div class="stat-mini" [style.borderColor]="'rgba(244,63,94,0.3)'">
          <div class="stat-num" style="color:var(--status-error)">{{ countByLevel('critical') }}</div>
          <div class="stat-lbl">Critical</div>
        </div>
        <div class="stat-mini" [style.borderColor]="'rgba(245,158,11,0.3)'">
          <div class="stat-num" style="color:var(--status-warning)">{{ countByLevel('warning') }}</div>
          <div class="stat-lbl">Warning</div>
        </div>
        <div class="stat-mini" [style.borderColor]="'rgba(79,142,247,0.3)'">
          <div class="stat-num" style="color:var(--accent-primary)">{{ countByLevel('info') }}</div>
          <div class="stat-lbl">Info</div>
        </div>
      </div>

      <!-- Filters -->
      <div class="filters-bar animate-fade-in-up">
        <select class="form-control filter-select" [(ngModel)]="filterLevel" (ngModelChange)="applyFilter()">
          <option value="">All Levels</option>
          <option value="critical">Critical</option>
          <option value="warning">Warning</option>
          <option value="info">Info</option>
        </select>
        <select class="form-control filter-select" [(ngModel)]="filterAck" (ngModelChange)="applyFilter()">
          <option value="">All Status</option>
          <option value="false">Unacknowledged</option>
          <option value="true">Acknowledged</option>
        </select>
        <select class="form-control filter-select" [(ngModel)]="filterCompany" (ngModelChange)="applyFilter()">
          <option value="">All Companies</option>
          @for (c of companies(); track c.id) {
            <option [value]="c.id">{{ c.name }}</option>
          }
        </select>
        <div class="alert-count">{{ filteredAlerts().length }} alert{{ filteredAlerts().length !== 1 ? 's' : '' }}</div>
      </div>

      <!-- Alerts List -->
      <div class="card animate-fade-in-up">
        @if (loading()) {
          <div class="loading-overlay"><div class="spinner"></div><span>Loading alerts…</span></div>
        } @else if (filteredAlerts().length === 0) {
          <div class="empty-state">
            <div class="empty-icon">✅</div>
            <div class="empty-title">No alerts found</div>
            <div class="empty-desc">Run an AI analysis to detect financial risks and anomalies</div>
          </div>
        } @else {
          <div class="alerts-feed">
            @for (alert of filteredAlerts(); track alert.id) {
              <div class="alert-row" [class.ack]="alert.acknowledged">
                <div class="alert-level-bar" [class]="'level-' + alert.level"></div>

                <div class="alert-body">
                  <div class="alert-top">
                    <span class="badge" [class]="'badge-' + levelBadge(alert.level)">
                      {{ levelIcon(alert.level) }} {{ alert.level }}
                    </span>
                    <span class="alert-company">{{ companyName(alert.company_id) }}</span>
                    @if (alert.acknowledged) {
                      <span class="badge badge-neutral">✓ Acknowledged</span>
                    }
                    <span class="alert-time monospace">{{ alert.created_at | slice:0:16 | replace:'T':' ' }}</span>
                  </div>
                  <div class="alert-message">{{ alert.message }}</div>
                </div>

                @if (!alert.acknowledged) {
                  <button class="btn-secondary btn-sm ack-btn" (click)="acknowledge(alert)" [disabled]="acking() === alert.id">
                    @if (acking() === alert.id) { Acknowledging… } @else { Acknowledge }
                  </button>
                }
              </div>
            }
          </div>
        }
      </div>
    </div>
  `,
    styles: [`
    .stat-mini {
      background: var(--bg-card);
      border: 1px solid;
      border-radius: var(--radius-md);
      padding: 16px 20px;
      display: flex;
      flex-direction: column;
      gap: 4px;
    }

    .stat-num  { font-size: 28px; font-weight: 700; }
    .stat-lbl  { font-size: 12px; text-transform: uppercase; letter-spacing: 0.8px; color: var(--text-secondary); }

    .filters-bar {
      display: flex;
      align-items: center;
      gap: 12px;
      flex-wrap: wrap;
    }

    .filter-select { max-width: 180px; }

    .alert-count { font-size: 13px; color: var(--text-secondary); margin-left: auto; }

    .alerts-feed { display: flex; flex-direction: column; gap: 1px; }

    .alert-row {
      display: flex;
      align-items: center;
      gap: 16px;
      padding: 14px 0;
      border-bottom: 1px solid var(--border-subtle);
      transition: background var(--transition-fast);

      &:last-child { border-bottom: none; }
      &:hover { background: rgba(79,142,247,0.02); }
      &.ack { opacity: 0.6; }
    }

    .alert-level-bar {
      width: 4px;
      height: 40px;
      border-radius: 2px;
      flex-shrink: 0;

      &.level-critical { background: var(--status-error); }
      &.level-warning  { background: var(--status-warning); }
      &.level-info     { background: var(--accent-primary); }
    }

    .alert-body { flex: 1; min-width: 0; display: flex; flex-direction: column; gap: 6px; }

    .alert-top {
      display: flex;
      align-items: center;
      gap: 10px;
      flex-wrap: wrap;
    }

    .alert-company { font-size: 12px; color: var(--text-secondary); font-weight: 500; }
    .alert-time    { font-size: 11px; color: var(--text-muted); margin-left: auto; }
    .alert-message { font-size: 13px; color: var(--text-primary); line-height: 1.5; }

    .ack-btn { flex-shrink: 0; }
  `]
})
export class AlertsComponent implements OnInit {
    private api = inject(ApiService);
    private toast = inject(ToastService);

    companies = signal<Company[]>([]);
    alerts = signal<Alert[]>([]);
    filteredAlerts = signal<Alert[]>([]);
    loading = signal(true);
    acking = signal<string | null>(null);
    filterLevel = '';
    filterAck = '';
    filterCompany = '';

    ngOnInit() {
        this.api.getCompanies().subscribe(cs => this.companies.set(cs));
        this.loadAlerts();
    }

    loadAlerts() {
        this.loading.set(true);
        this.api.getAlerts().subscribe({
            next: as => {
                this.alerts.set(as);
                this.applyFilter();
                this.loading.set(false);
            },
            error: () => { this.toast.error('Failed to load alerts'); this.loading.set(false); }
        });
    }

    applyFilter() {
        let filtered = this.alerts();
        if (this.filterLevel) filtered = filtered.filter(a => a.level === this.filterLevel);
        if (this.filterAck === 'true') filtered = filtered.filter(a => a.acknowledged);
        if (this.filterAck === 'false') filtered = filtered.filter(a => !a.acknowledged);
        if (this.filterCompany) filtered = filtered.filter(a => a.company_id === this.filterCompany);
        this.filteredAlerts.set(filtered);
    }

    acknowledge(alert: Alert) {
        this.acking.set(alert.id);
        this.api.acknowledgeAlert(alert.id).subscribe({
            next: updated => {
                this.alerts.update(as => as.map(a => a.id === updated.id ? updated : a));
                this.applyFilter();
                this.acking.set(null);
                this.toast.success('Alert acknowledged');
            },
            error: () => { this.acking.set(null); this.toast.error('Failed to acknowledge'); }
        });
    }

    countByLevel = (level: string) => this.alerts().filter(a => a.level === level).length;
    companyName = (id: string) => this.companies().find(c => c.id === id)?.name ?? '—';
    levelBadge = (l: string) => l === 'critical' ? 'danger' : l === 'warning' ? 'warning' : 'info';
    levelIcon = (l: string) => l === 'critical' ? '🔴' : l === 'warning' ? '🟡' : '🔵';
}
